# Site settings
title: '郑大侠'  # Your Title
tagline: 'To find something interesting'  # A brief tagline for your site
timezone: 'Asia/Guangzhou'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: kramdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
baseurl: # the subpath of your site, e.g. /blog/
codeurl: /code/
fragmenturl: /fragment/

# Personal info
avatar: https://avatars2.githubusercontent.com/u/6263631?v=3&s=460
email: yinweiniyu@163.com
github: https://github.com/dempeZheng
#weibo: //weibo.com/yoho92
music: //music.163.com/#/user/home?id=6758793
#twitter: https://twitter.com/zzchen9

# Logo setting
logocolor: '#000'
